spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update
app.jwt.secret = mysecret7f22c0ea264cf41bee7ea78fd1f6fde263f7fba62bb5670ab06188c6b7473346
app.jwt.expiration = 7200000
