spring.datasource.url=jdbc:postgresql://localhost:5432/Library
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update
app.jwt.secret = mysecret7f22c0ea264cf41bee7ea78fd1f6fde263f7fba62bb5670ab06188c6b7473346
app.jwt.expiration = 7200000
